# config/services.yaml
# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    avatars_directory: '%kernel.project_dir%/public/uploads/avatars'
    gemini_api_key: '%env(GEMINI_API_KEY)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'

    # Custom service configurations
    App\Service\CareersApiClient:
        arguments:
            $apiUsername: '%env(CAREERS_API_USERNAME)%'
            $apiPassword: '%env(CAREERS_API_PASSWORD)%'

    # Gemini AI Service configuration
    App\Service\GeminiAiService:
        arguments:
            $apiKey: '%gemini_api_key%'
        tags:
            - { name: 'monolog.logger', channel: 'ai' }

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
